# Generated by Django 5.2.10 on 2026-01-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("m1_runs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="type",
            field=models.CharField(
                choices=[
                    ("scene_spec", "场景规范"),
                    ("final_spec", "最终规范"),
                    ("dsl_draft", "DSL 草稿"),
                    ("draft_svg", "SVG 草稿"),
                    ("code", "代码"),
                ],
                max_length=50,
            ),
        ),
    ]
