# Generated by Django 5.2.10 on 2026-01-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m1_runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='inputs/')),
                ('params_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_submissions', to='m1_runs.run')),
            ],
            options={
                'db_table': 'input_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
