# Generated by Django 5.2.10 on 2026-01-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SvgDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="名称")),
                ("svg_content", models.TextField(verbose_name="SVG 内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "SVG 绘图",
                "verbose_name_plural": "SVG 绘图",
                "db_table": "svg_draw",
                "ordering": ["-created_at"],
            },
        ),
    ]
